<?xml version="1.0" encoding="utf-8"?><Database Name="mydatabase" Class="userlinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\mydatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="mydatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.admin" Member="admins">
    <Type Name="admin">
      <Column Name="a_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="a_name" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="a_password" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.customer" Member="customers">
    <Type Name="customer">
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="c_uname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="c_fname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="c_lname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="c_phone_no" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="c_gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="c_address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="c_country" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="c_state" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="c_city" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="c_pincode" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="c_dob" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="c_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="c_password" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="customer_feedback" Member="feedbacks" ThisKey="c_id" OtherKey="c_id" Type="feedback" />
      <Association Name="customer_order" Member="orders" ThisKey="c_id" OtherKey="c_id" Type="order" />
    </Type>
  </Table>
  <Table Name="dbo.employee" Member="employees">
    <Type Name="employee">
      <Column Name="e_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="e_fname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="e_lname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="e_phone_no" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="e_gender" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="e_address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="e_country" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="e_state" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="e_city" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="e_pincode" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Column Name="e_dob" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="e_doj" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="e_email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="e_salary" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.feedback" Member="feedbacks">
    <Type Name="feedback">
      <Column Name="f_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="f_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="customer_feedback" Member="customer" ThisKey="c_id" OtherKey="c_id" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.item" Member="items">
    <Type Name="item">
      <Column Name="i_no" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="i_image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="i_name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="i_details" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="i_price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="i_status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="i_disc" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.payment" Member="payments">
    <Type Name="payment">
      <Column Name="p_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="p_mode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="p_status" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="total_amount" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="o_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="p_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="order_payment" Member="order" ThisKey="o_id" OtherKey="o_id" Type="order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.city" Member="cities">
    <Type Name="city">
      <Column Name="cityId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cityname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="state_city" Member="state" ThisKey="stateId" OtherKey="stateId" Type="state" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.country" Member="countries">
    <Type Name="country">
      <Column Name="countryId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="countryname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="country_state" Member="states" ThisKey="countryId" OtherKey="countryId" Type="state" />
    </Type>
  </Table>
  <Table Name="dbo.state" Member="states">
    <Type Name="state">
      <Column Name="stateId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="countryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="statename" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="state_city" Member="cities" ThisKey="stateId" OtherKey="stateId" Type="city" />
      <Association Name="country_state" Member="country" ThisKey="countryId" OtherKey="countryId" Type="country" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[order]" Member="orders">
    <Type Name="order">
      <Column Name="o_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="o_qty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="o_status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="c_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="o_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="order_payment" Member="payments" ThisKey="o_id" OtherKey="o_id" Type="payment" />
      <Association Name="customer_order" Member="customer" ThisKey="c_id" OtherKey="c_id" Type="customer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>