#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace food_ordering_system.user
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="mydatabase")]
	public partial class userlinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin(admin instance);
    partial void Updateadmin(admin instance);
    partial void Deleteadmin(admin instance);
    partial void Insertcustomer(customer instance);
    partial void Updatecustomer(customer instance);
    partial void Deletecustomer(customer instance);
    partial void Insertemployee(employee instance);
    partial void Updateemployee(employee instance);
    partial void Deleteemployee(employee instance);
    partial void Insertfeedback(feedback instance);
    partial void Updatefeedback(feedback instance);
    partial void Deletefeedback(feedback instance);
    partial void Insertitem(item instance);
    partial void Updateitem(item instance);
    partial void Deleteitem(item instance);
    partial void Insertpayment(payment instance);
    partial void Updatepayment(payment instance);
    partial void Deletepayment(payment instance);
    partial void Insertcity(city instance);
    partial void Updatecity(city instance);
    partial void Deletecity(city instance);
    partial void Insertcountry(country instance);
    partial void Updatecountry(country instance);
    partial void Deletecountry(country instance);
    partial void Insertstate(state instance);
    partial void Updatestate(state instance);
    partial void Deletestate(state instance);
    partial void Insertorder(order instance);
    partial void Updateorder(order instance);
    partial void Deleteorder(order instance);
    #endregion
		
		public userlinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["mydatabaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public userlinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public userlinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public userlinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public userlinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin> admins
		{
			get
			{
				return this.GetTable<admin>();
			}
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<employee> employees
		{
			get
			{
				return this.GetTable<employee>();
			}
		}
		
		public System.Data.Linq.Table<feedback> feedbacks
		{
			get
			{
				return this.GetTable<feedback>();
			}
		}
		
		public System.Data.Linq.Table<item> items
		{
			get
			{
				return this.GetTable<item>();
			}
		}
		
		public System.Data.Linq.Table<payment> payments
		{
			get
			{
				return this.GetTable<payment>();
			}
		}
		
		public System.Data.Linq.Table<city> cities
		{
			get
			{
				return this.GetTable<city>();
			}
		}
		
		public System.Data.Linq.Table<country> countries
		{
			get
			{
				return this.GetTable<country>();
			}
		}
		
		public System.Data.Linq.Table<state> states
		{
			get
			{
				return this.GetTable<state>();
			}
		}
		
		public System.Data.Linq.Table<order> orders
		{
			get
			{
				return this.GetTable<order>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin")]
	public partial class admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _a_id;
		
		private string _a_name;
		
		private string _a_password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ona_idChanging(int value);
    partial void Ona_idChanged();
    partial void Ona_nameChanging(string value);
    partial void Ona_nameChanged();
    partial void Ona_passwordChanging(string value);
    partial void Ona_passwordChanged();
    #endregion
		
		public admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int a_id
		{
			get
			{
				return this._a_id;
			}
			set
			{
				if ((this._a_id != value))
				{
					this.Ona_idChanging(value);
					this.SendPropertyChanging();
					this._a_id = value;
					this.SendPropertyChanged("a_id");
					this.Ona_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_name", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string a_name
		{
			get
			{
				return this._a_name;
			}
			set
			{
				if ((this._a_name != value))
				{
					this.Ona_nameChanging(value);
					this.SendPropertyChanging();
					this._a_name = value;
					this.SendPropertyChanged("a_name");
					this.Ona_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_a_password", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string a_password
		{
			get
			{
				return this._a_password;
			}
			set
			{
				if ((this._a_password != value))
				{
					this.Ona_passwordChanging(value);
					this.SendPropertyChanging();
					this._a_password = value;
					this.SendPropertyChanged("a_password");
					this.Ona_passwordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customer")]
	public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _c_id;
		
		private string _c_uname;
		
		private string _c_fname;
		
		private string _c_lname;
		
		private decimal _c_phone_no;
		
		private string _c_gender;
		
		private string _c_address;
		
		private string _c_country;
		
		private string _c_state;
		
		private string _c_city;
		
		private decimal _c_pincode;
		
		private System.DateTime _c_dob;
		
		private string _c_email;
		
		private string _c_password;
		
		private EntitySet<feedback> _feedbacks;
		
		private EntitySet<order> _orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void Onc_unameChanging(string value);
    partial void Onc_unameChanged();
    partial void Onc_fnameChanging(string value);
    partial void Onc_fnameChanged();
    partial void Onc_lnameChanging(string value);
    partial void Onc_lnameChanged();
    partial void Onc_phone_noChanging(decimal value);
    partial void Onc_phone_noChanged();
    partial void Onc_genderChanging(string value);
    partial void Onc_genderChanged();
    partial void Onc_addressChanging(string value);
    partial void Onc_addressChanged();
    partial void Onc_countryChanging(string value);
    partial void Onc_countryChanged();
    partial void Onc_stateChanging(string value);
    partial void Onc_stateChanged();
    partial void Onc_cityChanging(string value);
    partial void Onc_cityChanged();
    partial void Onc_pincodeChanging(decimal value);
    partial void Onc_pincodeChanged();
    partial void Onc_dobChanging(System.DateTime value);
    partial void Onc_dobChanged();
    partial void Onc_emailChanging(string value);
    partial void Onc_emailChanged();
    partial void Onc_passwordChanging(string value);
    partial void Onc_passwordChanged();
    #endregion
		
		public customer()
		{
			this._feedbacks = new EntitySet<feedback>(new Action<feedback>(this.attach_feedbacks), new Action<feedback>(this.detach_feedbacks));
			this._orders = new EntitySet<order>(new Action<order>(this.attach_orders), new Action<order>(this.detach_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this.Onc_idChanging(value);
					this.SendPropertyChanging();
					this._c_id = value;
					this.SendPropertyChanged("c_id");
					this.Onc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_uname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string c_uname
		{
			get
			{
				return this._c_uname;
			}
			set
			{
				if ((this._c_uname != value))
				{
					this.Onc_unameChanging(value);
					this.SendPropertyChanging();
					this._c_uname = value;
					this.SendPropertyChanged("c_uname");
					this.Onc_unameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_fname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string c_fname
		{
			get
			{
				return this._c_fname;
			}
			set
			{
				if ((this._c_fname != value))
				{
					this.Onc_fnameChanging(value);
					this.SendPropertyChanging();
					this._c_fname = value;
					this.SendPropertyChanged("c_fname");
					this.Onc_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_lname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string c_lname
		{
			get
			{
				return this._c_lname;
			}
			set
			{
				if ((this._c_lname != value))
				{
					this.Onc_lnameChanging(value);
					this.SendPropertyChanging();
					this._c_lname = value;
					this.SendPropertyChanged("c_lname");
					this.Onc_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_phone_no", DbType="Decimal(10,0) NOT NULL")]
		public decimal c_phone_no
		{
			get
			{
				return this._c_phone_no;
			}
			set
			{
				if ((this._c_phone_no != value))
				{
					this.Onc_phone_noChanging(value);
					this.SendPropertyChanging();
					this._c_phone_no = value;
					this.SendPropertyChanged("c_phone_no");
					this.Onc_phone_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string c_gender
		{
			get
			{
				return this._c_gender;
			}
			set
			{
				if ((this._c_gender != value))
				{
					this.Onc_genderChanging(value);
					this.SendPropertyChanging();
					this._c_gender = value;
					this.SendPropertyChanged("c_gender");
					this.Onc_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_address", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string c_address
		{
			get
			{
				return this._c_address;
			}
			set
			{
				if ((this._c_address != value))
				{
					this.Onc_addressChanging(value);
					this.SendPropertyChanging();
					this._c_address = value;
					this.SendPropertyChanged("c_address");
					this.Onc_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_country", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string c_country
		{
			get
			{
				return this._c_country;
			}
			set
			{
				if ((this._c_country != value))
				{
					this.Onc_countryChanging(value);
					this.SendPropertyChanging();
					this._c_country = value;
					this.SendPropertyChanged("c_country");
					this.Onc_countryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_state", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string c_state
		{
			get
			{
				return this._c_state;
			}
			set
			{
				if ((this._c_state != value))
				{
					this.Onc_stateChanging(value);
					this.SendPropertyChanging();
					this._c_state = value;
					this.SendPropertyChanged("c_state");
					this.Onc_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_city", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string c_city
		{
			get
			{
				return this._c_city;
			}
			set
			{
				if ((this._c_city != value))
				{
					this.Onc_cityChanging(value);
					this.SendPropertyChanging();
					this._c_city = value;
					this.SendPropertyChanged("c_city");
					this.Onc_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_pincode", DbType="Decimal(10,0) NOT NULL")]
		public decimal c_pincode
		{
			get
			{
				return this._c_pincode;
			}
			set
			{
				if ((this._c_pincode != value))
				{
					this.Onc_pincodeChanging(value);
					this.SendPropertyChanging();
					this._c_pincode = value;
					this.SendPropertyChanged("c_pincode");
					this.Onc_pincodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_dob", DbType="Date NOT NULL")]
		public System.DateTime c_dob
		{
			get
			{
				return this._c_dob;
			}
			set
			{
				if ((this._c_dob != value))
				{
					this.Onc_dobChanging(value);
					this.SendPropertyChanging();
					this._c_dob = value;
					this.SendPropertyChanged("c_dob");
					this.Onc_dobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string c_email
		{
			get
			{
				return this._c_email;
			}
			set
			{
				if ((this._c_email != value))
				{
					this.Onc_emailChanging(value);
					this.SendPropertyChanging();
					this._c_email = value;
					this.SendPropertyChanged("c_email");
					this.Onc_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_password", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string c_password
		{
			get
			{
				return this._c_password;
			}
			set
			{
				if ((this._c_password != value))
				{
					this.Onc_passwordChanging(value);
					this.SendPropertyChanging();
					this._c_password = value;
					this.SendPropertyChanged("c_password");
					this.Onc_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_feedback", Storage="_feedbacks", ThisKey="c_id", OtherKey="c_id")]
		public EntitySet<feedback> feedbacks
		{
			get
			{
				return this._feedbacks;
			}
			set
			{
				this._feedbacks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_order", Storage="_orders", ThisKey="c_id", OtherKey="c_id")]
		public EntitySet<order> orders
		{
			get
			{
				return this._orders;
			}
			set
			{
				this._orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_feedbacks(feedback entity)
		{
			this.SendPropertyChanging();
			entity.customer = this;
		}
		
		private void detach_feedbacks(feedback entity)
		{
			this.SendPropertyChanging();
			entity.customer = null;
		}
		
		private void attach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.customer = this;
		}
		
		private void detach_orders(order entity)
		{
			this.SendPropertyChanging();
			entity.customer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employee")]
	public partial class employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _e_id;
		
		private string _e_fname;
		
		private string _e_lname;
		
		private decimal _e_phone_no;
		
		private string _e_gender;
		
		private string _e_address;
		
		private string _e_country;
		
		private string _e_state;
		
		private string _e_city;
		
		private decimal _e_pincode;
		
		private System.DateTime _e_dob;
		
		private System.DateTime _e_doj;
		
		private string _e_email;
		
		private System.Nullable<decimal> _e_salary;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void One_idChanging(int value);
    partial void One_idChanged();
    partial void One_fnameChanging(string value);
    partial void One_fnameChanged();
    partial void One_lnameChanging(string value);
    partial void One_lnameChanged();
    partial void One_phone_noChanging(decimal value);
    partial void One_phone_noChanged();
    partial void One_genderChanging(string value);
    partial void One_genderChanged();
    partial void One_addressChanging(string value);
    partial void One_addressChanged();
    partial void One_countryChanging(string value);
    partial void One_countryChanged();
    partial void One_stateChanging(string value);
    partial void One_stateChanged();
    partial void One_cityChanging(string value);
    partial void One_cityChanged();
    partial void One_pincodeChanging(decimal value);
    partial void One_pincodeChanged();
    partial void One_dobChanging(System.DateTime value);
    partial void One_dobChanged();
    partial void One_dojChanging(System.DateTime value);
    partial void One_dojChanged();
    partial void One_emailChanging(string value);
    partial void One_emailChanged();
    partial void One_salaryChanging(System.Nullable<decimal> value);
    partial void One_salaryChanged();
    #endregion
		
		public employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int e_id
		{
			get
			{
				return this._e_id;
			}
			set
			{
				if ((this._e_id != value))
				{
					this.One_idChanging(value);
					this.SendPropertyChanging();
					this._e_id = value;
					this.SendPropertyChanged("e_id");
					this.One_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_fname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string e_fname
		{
			get
			{
				return this._e_fname;
			}
			set
			{
				if ((this._e_fname != value))
				{
					this.One_fnameChanging(value);
					this.SendPropertyChanging();
					this._e_fname = value;
					this.SendPropertyChanged("e_fname");
					this.One_fnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_lname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string e_lname
		{
			get
			{
				return this._e_lname;
			}
			set
			{
				if ((this._e_lname != value))
				{
					this.One_lnameChanging(value);
					this.SendPropertyChanging();
					this._e_lname = value;
					this.SendPropertyChanged("e_lname");
					this.One_lnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_phone_no", DbType="Decimal(10,0) NOT NULL")]
		public decimal e_phone_no
		{
			get
			{
				return this._e_phone_no;
			}
			set
			{
				if ((this._e_phone_no != value))
				{
					this.One_phone_noChanging(value);
					this.SendPropertyChanging();
					this._e_phone_no = value;
					this.SendPropertyChanged("e_phone_no");
					this.One_phone_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_gender", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string e_gender
		{
			get
			{
				return this._e_gender;
			}
			set
			{
				if ((this._e_gender != value))
				{
					this.One_genderChanging(value);
					this.SendPropertyChanging();
					this._e_gender = value;
					this.SendPropertyChanged("e_gender");
					this.One_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string e_address
		{
			get
			{
				return this._e_address;
			}
			set
			{
				if ((this._e_address != value))
				{
					this.One_addressChanging(value);
					this.SendPropertyChanging();
					this._e_address = value;
					this.SendPropertyChanged("e_address");
					this.One_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_country", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string e_country
		{
			get
			{
				return this._e_country;
			}
			set
			{
				if ((this._e_country != value))
				{
					this.One_countryChanging(value);
					this.SendPropertyChanging();
					this._e_country = value;
					this.SendPropertyChanged("e_country");
					this.One_countryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_state", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string e_state
		{
			get
			{
				return this._e_state;
			}
			set
			{
				if ((this._e_state != value))
				{
					this.One_stateChanging(value);
					this.SendPropertyChanging();
					this._e_state = value;
					this.SendPropertyChanged("e_state");
					this.One_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_city", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string e_city
		{
			get
			{
				return this._e_city;
			}
			set
			{
				if ((this._e_city != value))
				{
					this.One_cityChanging(value);
					this.SendPropertyChanging();
					this._e_city = value;
					this.SendPropertyChanged("e_city");
					this.One_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_pincode", DbType="Decimal(10,0) NOT NULL")]
		public decimal e_pincode
		{
			get
			{
				return this._e_pincode;
			}
			set
			{
				if ((this._e_pincode != value))
				{
					this.One_pincodeChanging(value);
					this.SendPropertyChanging();
					this._e_pincode = value;
					this.SendPropertyChanged("e_pincode");
					this.One_pincodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_dob", DbType="Date NOT NULL")]
		public System.DateTime e_dob
		{
			get
			{
				return this._e_dob;
			}
			set
			{
				if ((this._e_dob != value))
				{
					this.One_dobChanging(value);
					this.SendPropertyChanging();
					this._e_dob = value;
					this.SendPropertyChanged("e_dob");
					this.One_dobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_doj", DbType="Date NOT NULL")]
		public System.DateTime e_doj
		{
			get
			{
				return this._e_doj;
			}
			set
			{
				if ((this._e_doj != value))
				{
					this.One_dojChanging(value);
					this.SendPropertyChanging();
					this._e_doj = value;
					this.SendPropertyChanged("e_doj");
					this.One_dojChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string e_email
		{
			get
			{
				return this._e_email;
			}
			set
			{
				if ((this._e_email != value))
				{
					this.One_emailChanging(value);
					this.SendPropertyChanging();
					this._e_email = value;
					this.SendPropertyChanged("e_email");
					this.One_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_e_salary", DbType="Money")]
		public System.Nullable<decimal> e_salary
		{
			get
			{
				return this._e_salary;
			}
			set
			{
				if ((this._e_salary != value))
				{
					this.One_salaryChanging(value);
					this.SendPropertyChanging();
					this._e_salary = value;
					this.SendPropertyChanged("e_salary");
					this.One_salaryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.feedback")]
	public partial class feedback : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _f_id;
		
		private int _c_id;
		
		private string _f_name;
		
		private EntityRef<customer> _customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onf_idChanging(int value);
    partial void Onf_idChanged();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void Onf_nameChanging(string value);
    partial void Onf_nameChanged();
    #endregion
		
		public feedback()
		{
			this._customer = default(EntityRef<customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int f_id
		{
			get
			{
				return this._f_id;
			}
			set
			{
				if ((this._f_id != value))
				{
					this.Onf_idChanging(value);
					this.SendPropertyChanging();
					this._f_id = value;
					this.SendPropertyChanged("f_id");
					this.Onf_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int NOT NULL")]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					if (this._customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onc_idChanging(value);
					this.SendPropertyChanging();
					this._c_id = value;
					this.SendPropertyChanged("c_id");
					this.Onc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_f_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string f_name
		{
			get
			{
				return this._f_name;
			}
			set
			{
				if ((this._f_name != value))
				{
					this.Onf_nameChanging(value);
					this.SendPropertyChanging();
					this._f_name = value;
					this.SendPropertyChanged("f_name");
					this.Onf_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_feedback", Storage="_customer", ThisKey="c_id", OtherKey="c_id", IsForeignKey=true)]
		public customer customer
		{
			get
			{
				return this._customer.Entity;
			}
			set
			{
				customer previousValue = this._customer.Entity;
				if (((previousValue != value) 
							|| (this._customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._customer.Entity = null;
						previousValue.feedbacks.Remove(this);
					}
					this._customer.Entity = value;
					if ((value != null))
					{
						value.feedbacks.Add(this);
						this._c_id = value.c_id;
					}
					else
					{
						this._c_id = default(int);
					}
					this.SendPropertyChanged("customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.item")]
	public partial class item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_no;
		
		private string _i_image;
		
		private string _i_name;
		
		private string _i_details;
		
		private double _i_price;
		
		private string _i_status;
		
		private System.Nullable<decimal> _i_disc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_noChanging(int value);
    partial void Oni_noChanged();
    partial void Oni_imageChanging(string value);
    partial void Oni_imageChanged();
    partial void Oni_nameChanging(string value);
    partial void Oni_nameChanged();
    partial void Oni_detailsChanging(string value);
    partial void Oni_detailsChanged();
    partial void Oni_priceChanging(double value);
    partial void Oni_priceChanged();
    partial void Oni_statusChanging(string value);
    partial void Oni_statusChanged();
    partial void Oni_discChanging(System.Nullable<decimal> value);
    partial void Oni_discChanged();
    #endregion
		
		public item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_no", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i_no
		{
			get
			{
				return this._i_no;
			}
			set
			{
				if ((this._i_no != value))
				{
					this.Oni_noChanging(value);
					this.SendPropertyChanging();
					this._i_no = value;
					this.SendPropertyChanged("i_no");
					this.Oni_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_image", DbType="VarChar(MAX)")]
		public string i_image
		{
			get
			{
				return this._i_image;
			}
			set
			{
				if ((this._i_image != value))
				{
					this.Oni_imageChanging(value);
					this.SendPropertyChanging();
					this._i_image = value;
					this.SendPropertyChanged("i_image");
					this.Oni_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string i_name
		{
			get
			{
				return this._i_name;
			}
			set
			{
				if ((this._i_name != value))
				{
					this.Oni_nameChanging(value);
					this.SendPropertyChanging();
					this._i_name = value;
					this.SendPropertyChanged("i_name");
					this.Oni_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_details", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string i_details
		{
			get
			{
				return this._i_details;
			}
			set
			{
				if ((this._i_details != value))
				{
					this.Oni_detailsChanging(value);
					this.SendPropertyChanging();
					this._i_details = value;
					this.SendPropertyChanged("i_details");
					this.Oni_detailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_price", DbType="Float NOT NULL")]
		public double i_price
		{
			get
			{
				return this._i_price;
			}
			set
			{
				if ((this._i_price != value))
				{
					this.Oni_priceChanging(value);
					this.SendPropertyChanging();
					this._i_price = value;
					this.SendPropertyChanged("i_price");
					this.Oni_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string i_status
		{
			get
			{
				return this._i_status;
			}
			set
			{
				if ((this._i_status != value))
				{
					this.Oni_statusChanging(value);
					this.SendPropertyChanging();
					this._i_status = value;
					this.SendPropertyChanged("i_status");
					this.Oni_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_disc", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> i_disc
		{
			get
			{
				return this._i_disc;
			}
			set
			{
				if ((this._i_disc != value))
				{
					this.Oni_discChanging(value);
					this.SendPropertyChanging();
					this._i_disc = value;
					this.SendPropertyChanged("i_disc");
					this.Oni_discChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.payment")]
	public partial class payment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _p_id;
		
		private string _p_mode;
		
		private string _p_status;
		
		private double _total_amount;
		
		private int _o_id;
		
		private System.Nullable<System.DateTime> _p_date;
		
		private EntityRef<order> _order;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onp_idChanging(int value);
    partial void Onp_idChanged();
    partial void Onp_modeChanging(string value);
    partial void Onp_modeChanged();
    partial void Onp_statusChanging(string value);
    partial void Onp_statusChanged();
    partial void Ontotal_amountChanging(double value);
    partial void Ontotal_amountChanged();
    partial void Ono_idChanging(int value);
    partial void Ono_idChanged();
    partial void Onp_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onp_dateChanged();
    #endregion
		
		public payment()
		{
			this._order = default(EntityRef<order>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int p_id
		{
			get
			{
				return this._p_id;
			}
			set
			{
				if ((this._p_id != value))
				{
					this.Onp_idChanging(value);
					this.SendPropertyChanging();
					this._p_id = value;
					this.SendPropertyChanged("p_id");
					this.Onp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_mode", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string p_mode
		{
			get
			{
				return this._p_mode;
			}
			set
			{
				if ((this._p_mode != value))
				{
					this.Onp_modeChanging(value);
					this.SendPropertyChanging();
					this._p_mode = value;
					this.SendPropertyChanged("p_mode");
					this.Onp_modeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_status", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string p_status
		{
			get
			{
				return this._p_status;
			}
			set
			{
				if ((this._p_status != value))
				{
					this.Onp_statusChanging(value);
					this.SendPropertyChanging();
					this._p_status = value;
					this.SendPropertyChanged("p_status");
					this.Onp_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_amount", DbType="Float NOT NULL")]
		public double total_amount
		{
			get
			{
				return this._total_amount;
			}
			set
			{
				if ((this._total_amount != value))
				{
					this.Ontotal_amountChanging(value);
					this.SendPropertyChanging();
					this._total_amount = value;
					this.SendPropertyChanged("total_amount");
					this.Ontotal_amountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_id", DbType="Int NOT NULL")]
		public int o_id
		{
			get
			{
				return this._o_id;
			}
			set
			{
				if ((this._o_id != value))
				{
					if (this._order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ono_idChanging(value);
					this.SendPropertyChanging();
					this._o_id = value;
					this.SendPropertyChanged("o_id");
					this.Ono_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_date", DbType="Date")]
		public System.Nullable<System.DateTime> p_date
		{
			get
			{
				return this._p_date;
			}
			set
			{
				if ((this._p_date != value))
				{
					this.Onp_dateChanging(value);
					this.SendPropertyChanging();
					this._p_date = value;
					this.SendPropertyChanged("p_date");
					this.Onp_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_payment", Storage="_order", ThisKey="o_id", OtherKey="o_id", IsForeignKey=true)]
		public order order
		{
			get
			{
				return this._order.Entity;
			}
			set
			{
				order previousValue = this._order.Entity;
				if (((previousValue != value) 
							|| (this._order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._order.Entity = null;
						previousValue.payments.Remove(this);
					}
					this._order.Entity = value;
					if ((value != null))
					{
						value.payments.Add(this);
						this._o_id = value.o_id;
					}
					else
					{
						this._o_id = default(int);
					}
					this.SendPropertyChanged("order");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.city")]
	public partial class city : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cityId;
		
		private int _stateId;
		
		private string _cityname;
		
		private EntityRef<state> _state;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncityIdChanging(int value);
    partial void OncityIdChanged();
    partial void OnstateIdChanging(int value);
    partial void OnstateIdChanged();
    partial void OncitynameChanging(string value);
    partial void OncitynameChanged();
    #endregion
		
		public city()
		{
			this._state = default(EntityRef<state>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int cityId
		{
			get
			{
				return this._cityId;
			}
			set
			{
				if ((this._cityId != value))
				{
					this.OncityIdChanging(value);
					this.SendPropertyChanging();
					this._cityId = value;
					this.SendPropertyChanged("cityId");
					this.OncityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateId", DbType="Int NOT NULL")]
		public int stateId
		{
			get
			{
				return this._stateId;
			}
			set
			{
				if ((this._stateId != value))
				{
					if (this._state.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstateIdChanging(value);
					this.SendPropertyChanging();
					this._stateId = value;
					this.SendPropertyChanged("stateId");
					this.OnstateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cityname
		{
			get
			{
				return this._cityname;
			}
			set
			{
				if ((this._cityname != value))
				{
					this.OncitynameChanging(value);
					this.SendPropertyChanging();
					this._cityname = value;
					this.SendPropertyChanged("cityname");
					this.OncitynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="state_city", Storage="_state", ThisKey="stateId", OtherKey="stateId", IsForeignKey=true)]
		public state state
		{
			get
			{
				return this._state.Entity;
			}
			set
			{
				state previousValue = this._state.Entity;
				if (((previousValue != value) 
							|| (this._state.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._state.Entity = null;
						previousValue.cities.Remove(this);
					}
					this._state.Entity = value;
					if ((value != null))
					{
						value.cities.Add(this);
						this._stateId = value.stateId;
					}
					else
					{
						this._stateId = default(int);
					}
					this.SendPropertyChanged("state");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.country")]
	public partial class country : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _countryId;
		
		private string _countryname;
		
		private EntitySet<state> _states;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncountryIdChanging(int value);
    partial void OncountryIdChanged();
    partial void OncountrynameChanging(string value);
    partial void OncountrynameChanged();
    #endregion
		
		public country()
		{
			this._states = new EntitySet<state>(new Action<state>(this.attach_states), new Action<state>(this.detach_states));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countryId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int countryId
		{
			get
			{
				return this._countryId;
			}
			set
			{
				if ((this._countryId != value))
				{
					this.OncountryIdChanging(value);
					this.SendPropertyChanging();
					this._countryId = value;
					this.SendPropertyChanged("countryId");
					this.OncountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countryname", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string countryname
		{
			get
			{
				return this._countryname;
			}
			set
			{
				if ((this._countryname != value))
				{
					this.OncountrynameChanging(value);
					this.SendPropertyChanging();
					this._countryname = value;
					this.SendPropertyChanged("countryname");
					this.OncountrynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="country_state", Storage="_states", ThisKey="countryId", OtherKey="countryId")]
		public EntitySet<state> states
		{
			get
			{
				return this._states;
			}
			set
			{
				this._states.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_states(state entity)
		{
			this.SendPropertyChanging();
			entity.country = this;
		}
		
		private void detach_states(state entity)
		{
			this.SendPropertyChanging();
			entity.country = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.state")]
	public partial class state : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stateId;
		
		private int _countryId;
		
		private string _statename;
		
		private EntitySet<city> _cities;
		
		private EntityRef<country> _country;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstateIdChanging(int value);
    partial void OnstateIdChanged();
    partial void OncountryIdChanging(int value);
    partial void OncountryIdChanged();
    partial void OnstatenameChanging(string value);
    partial void OnstatenameChanged();
    #endregion
		
		public state()
		{
			this._cities = new EntitySet<city>(new Action<city>(this.attach_cities), new Action<city>(this.detach_cities));
			this._country = default(EntityRef<country>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int stateId
		{
			get
			{
				return this._stateId;
			}
			set
			{
				if ((this._stateId != value))
				{
					this.OnstateIdChanging(value);
					this.SendPropertyChanging();
					this._stateId = value;
					this.SendPropertyChanged("stateId");
					this.OnstateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_countryId", DbType="Int NOT NULL")]
		public int countryId
		{
			get
			{
				return this._countryId;
			}
			set
			{
				if ((this._countryId != value))
				{
					if (this._country.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncountryIdChanging(value);
					this.SendPropertyChanging();
					this._countryId = value;
					this.SendPropertyChanged("countryId");
					this.OncountryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statename", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string statename
		{
			get
			{
				return this._statename;
			}
			set
			{
				if ((this._statename != value))
				{
					this.OnstatenameChanging(value);
					this.SendPropertyChanging();
					this._statename = value;
					this.SendPropertyChanged("statename");
					this.OnstatenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="state_city", Storage="_cities", ThisKey="stateId", OtherKey="stateId")]
		public EntitySet<city> cities
		{
			get
			{
				return this._cities;
			}
			set
			{
				this._cities.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="country_state", Storage="_country", ThisKey="countryId", OtherKey="countryId", IsForeignKey=true)]
		public country country
		{
			get
			{
				return this._country.Entity;
			}
			set
			{
				country previousValue = this._country.Entity;
				if (((previousValue != value) 
							|| (this._country.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._country.Entity = null;
						previousValue.states.Remove(this);
					}
					this._country.Entity = value;
					if ((value != null))
					{
						value.states.Add(this);
						this._countryId = value.countryId;
					}
					else
					{
						this._countryId = default(int);
					}
					this.SendPropertyChanged("country");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cities(city entity)
		{
			this.SendPropertyChanging();
			entity.state = this;
		}
		
		private void detach_cities(city entity)
		{
			this.SendPropertyChanging();
			entity.state = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[order]")]
	public partial class order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _o_id;
		
		private int _o_qty;
		
		private string _o_status;
		
		private int _c_id;
		
		private System.Nullable<System.DateTime> _o_date;
		
		private EntitySet<payment> _payments;
		
		private EntityRef<customer> _customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ono_idChanging(int value);
    partial void Ono_idChanged();
    partial void Ono_qtyChanging(int value);
    partial void Ono_qtyChanged();
    partial void Ono_statusChanging(string value);
    partial void Ono_statusChanged();
    partial void Onc_idChanging(int value);
    partial void Onc_idChanged();
    partial void Ono_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ono_dateChanged();
    #endregion
		
		public order()
		{
			this._payments = new EntitySet<payment>(new Action<payment>(this.attach_payments), new Action<payment>(this.detach_payments));
			this._customer = default(EntityRef<customer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int o_id
		{
			get
			{
				return this._o_id;
			}
			set
			{
				if ((this._o_id != value))
				{
					this.Ono_idChanging(value);
					this.SendPropertyChanging();
					this._o_id = value;
					this.SendPropertyChanged("o_id");
					this.Ono_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_qty", DbType="Int NOT NULL")]
		public int o_qty
		{
			get
			{
				return this._o_qty;
			}
			set
			{
				if ((this._o_qty != value))
				{
					this.Ono_qtyChanging(value);
					this.SendPropertyChanging();
					this._o_qty = value;
					this.SendPropertyChanged("o_qty");
					this.Ono_qtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_status", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string o_status
		{
			get
			{
				return this._o_status;
			}
			set
			{
				if ((this._o_status != value))
				{
					this.Ono_statusChanging(value);
					this.SendPropertyChanging();
					this._o_status = value;
					this.SendPropertyChanged("o_status");
					this.Ono_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int NOT NULL")]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					if (this._customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onc_idChanging(value);
					this.SendPropertyChanging();
					this._c_id = value;
					this.SendPropertyChanged("c_id");
					this.Onc_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> o_date
		{
			get
			{
				return this._o_date;
			}
			set
			{
				if ((this._o_date != value))
				{
					this.Ono_dateChanging(value);
					this.SendPropertyChanging();
					this._o_date = value;
					this.SendPropertyChanged("o_date");
					this.Ono_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="order_payment", Storage="_payments", ThisKey="o_id", OtherKey="o_id")]
		public EntitySet<payment> payments
		{
			get
			{
				return this._payments;
			}
			set
			{
				this._payments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="customer_order", Storage="_customer", ThisKey="c_id", OtherKey="c_id", IsForeignKey=true)]
		public customer customer
		{
			get
			{
				return this._customer.Entity;
			}
			set
			{
				customer previousValue = this._customer.Entity;
				if (((previousValue != value) 
							|| (this._customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._customer.Entity = null;
						previousValue.orders.Remove(this);
					}
					this._customer.Entity = value;
					if ((value != null))
					{
						value.orders.Add(this);
						this._c_id = value.c_id;
					}
					else
					{
						this._c_id = default(int);
					}
					this.SendPropertyChanged("customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_payments(payment entity)
		{
			this.SendPropertyChanging();
			entity.order = this;
		}
		
		private void detach_payments(payment entity)
		{
			this.SendPropertyChanging();
			entity.order = null;
		}
	}
}
#pragma warning restore 1591
